# Generated by Django 2.1.4 on 2019-01-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EndpointRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('method', models.CharField(choices=[('GET', 0), ('HEAD', 1), ('POST', 2), ('PUT', 3), ('DELETE', 4), ('CONNECT', 5), ('OPTIONS', 6), ('TRACE', 7), ('PATCH', 8)], default='GET', max_length=10)),
                ('uri', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
